/**
 * Pure data + types for the admin seed wizard. Lives outside the
 * `'use server'` boundary in `admin-seed.ts` so the synchronous
 * `buildSeedPlan` planner can be imported into server components
 * (the wizard's Phase 1 inventory) without violating Next 16's
 * "Server Actions must be async functions" rule.
 *
 * The dataset aims to reproduce a semi-believable six months of a
 * single working adult's spending — bi-weekly salary, rent on the
 * 1st, real-priced subscriptions, weekly grocery runs, coffee-shop
 * habit, occasional clothing splurges, etc — so the dashboard
 * heatmap, charts, budgets, and recurring widgets are populated
 * enough to demo without staring at a near-empty UI.
 */

export interface SeedAccount {
    name: string;
    type: 'checking' | 'savings' | 'credit_card';
    currency: 'USD';
    openingBalance: number; // minor units
}

export interface SeedCategory {
    name: string;
    type: 'income' | 'expense';
}

export interface SeedBudget {
    categoryName: string;
    monthlyAmount: number; // minor units
}

export interface SeedTemplate {
    description: string;
    cadence:
        | { kind: 'monthly'; dayOfMonth: number }
        | { kind: 'biweekly'; dayOfWeek: number };
    type: 'income' | 'expense';
    amount: number; // minor units
    accountName: string;
    categoryName: string;
}

export interface SeedPlan {
    version: string;
    items: Array<{ kind: string; count: number; note?: string }>;
    accounts: SeedAccount[];
    categories: SeedCategory[];
    budgets: SeedBudget[];
    templates: SeedTemplate[];
    /** Approximate per-month transaction count generated by the procedural pass. */
    proceduralTransactionsPerMonth: number;
    monthsBack: number;
}

export const SEED_VERSION = 'v2';

export function buildSeedPlan(): SeedPlan {
    const accounts: SeedAccount[] = [
        { name: 'Checking', type: 'checking', currency: 'USD', openingBalance: 250_000 },
        { name: 'Savings', type: 'savings', currency: 'USD', openingBalance: 500_000 },
        { name: 'Credit card', type: 'credit_card', currency: 'USD', openingBalance: 0 },
    ];

    const categories: SeedCategory[] = [
        // income
        { name: 'Salary', type: 'income' },
        { name: 'Bonus', type: 'income' },
        { name: 'Freelance', type: 'income' },
        // expense
        { name: 'Rent', type: 'expense' },
        { name: 'Groceries', type: 'expense' },
        { name: 'Dining', type: 'expense' },
        { name: 'Coffee', type: 'expense' },
        { name: 'Transport', type: 'expense' },
        { name: 'Gas', type: 'expense' },
        { name: 'Utilities', type: 'expense' },
        { name: 'Internet', type: 'expense' },
        { name: 'Phone', type: 'expense' },
        { name: 'Subscriptions', type: 'expense' },
        { name: 'Clothing', type: 'expense' },
        { name: 'Entertainment', type: 'expense' },
        { name: 'Health', type: 'expense' },
        { name: 'Gym', type: 'expense' },
        { name: 'Personal care', type: 'expense' },
        { name: 'Home goods', type: 'expense' },
    ];

    const budgets: SeedBudget[] = [
        { categoryName: 'Groceries', monthlyAmount: 60_000 },
        { categoryName: 'Dining', monthlyAmount: 30_000 },
        { categoryName: 'Coffee', monthlyAmount: 8_000 },
        { categoryName: 'Transport', monthlyAmount: 20_000 },
        { categoryName: 'Subscriptions', monthlyAmount: 10_000 },
        { categoryName: 'Entertainment', monthlyAmount: 15_000 },
        { categoryName: 'Clothing', monthlyAmount: 15_000 },
    ];

    // Real-world US prices (Nov 2026 approx) for the streaming-and-
    // services bundle most people stack. Updating as needed is a
    // one-line tweak per row.
    const templates: SeedTemplate[] = [
        // ---- income ----
        {
            description: 'Salary (bi-weekly)',
            cadence: { kind: 'biweekly', dayOfWeek: 5 }, // Friday
            type: 'income',
            amount: 320_000, // $3,200/paycheck → ~$6,933/mo gross
            accountName: 'Checking',
            categoryName: 'Salary',
        },
        // ---- monthly fixed expenses ----
        {
            description: 'Rent',
            cadence: { kind: 'monthly', dayOfMonth: 1 },
            type: 'expense',
            amount: 180_000, // $1,800
            accountName: 'Checking',
            categoryName: 'Rent',
        },
        {
            description: 'Internet (Comcast)',
            cadence: { kind: 'monthly', dayOfMonth: 5 },
            type: 'expense',
            amount: 6_500, // $65
            accountName: 'Checking',
            categoryName: 'Internet',
        },
        {
            description: 'Phone bill (T-Mobile)',
            cadence: { kind: 'monthly', dayOfMonth: 15 },
            type: 'expense',
            amount: 5_500, // $55
            accountName: 'Checking',
            categoryName: 'Phone',
        },
        {
            description: 'Gym membership',
            cadence: { kind: 'monthly', dayOfMonth: 1 },
            type: 'expense',
            amount: 3_500, // $35
            accountName: 'Checking',
            categoryName: 'Gym',
        },
        // ---- streaming + service subscriptions (real prices) ----
        {
            description: 'Netflix Standard',
            cadence: { kind: 'monthly', dayOfMonth: 7 },
            type: 'expense',
            amount: 1_549, // $15.49
            accountName: 'Credit card',
            categoryName: 'Subscriptions',
        },
        {
            description: 'Spotify Premium',
            cadence: { kind: 'monthly', dayOfMonth: 10 },
            type: 'expense',
            amount: 1_199, // $11.99
            accountName: 'Credit card',
            categoryName: 'Subscriptions',
        },
        {
            description: 'YouTube Premium',
            cadence: { kind: 'monthly', dayOfMonth: 12 },
            type: 'expense',
            amount: 1_399, // $13.99
            accountName: 'Credit card',
            categoryName: 'Subscriptions',
        },
        {
            description: 'Disney+ with ads',
            cadence: { kind: 'monthly', dayOfMonth: 14 },
            type: 'expense',
            amount: 999, // $9.99
            accountName: 'Credit card',
            categoryName: 'Subscriptions',
        },
        {
            description: 'Amazon Prime',
            cadence: { kind: 'monthly', dayOfMonth: 18 },
            type: 'expense',
            amount: 1_499, // $14.99
            accountName: 'Credit card',
            categoryName: 'Subscriptions',
        },
        {
            description: 'iCloud+ 200GB',
            cadence: { kind: 'monthly', dayOfMonth: 22 },
            type: 'expense',
            amount: 299, // $2.99
            accountName: 'Credit card',
            categoryName: 'Subscriptions',
        },
        {
            description: 'ChatGPT Plus',
            cadence: { kind: 'monthly', dayOfMonth: 25 },
            type: 'expense',
            amount: 2_000, // $20.00
            accountName: 'Credit card',
            categoryName: 'Subscriptions',
        },
    ];

    const monthsBack = 6;
    // Procedural transactions per month: groceries (~10), dining (~10),
    // coffee (~18), gas (~3), transport/uber (~2), utilities (~1),
    // clothing occasional, entertainment (~2), health (~1), home (~1),
    // personal care (~1), freelance bonus rare. Mean ~50/month.
    const proceduralTransactionsPerMonth = 50;
    const proceduralTotal = proceduralTransactionsPerMonth * monthsBack;
    // Template materializations over the past 6 months:
    //   - biweekly: ~13 occurrences (26/year)
    //   - 11 monthly templates × 6 months = 66
    //   - Total = ~79
    const templateMaterializations = 13 + 11 * monthsBack;

    const items: SeedPlan['items'] = [
        { kind: 'Accounts', count: accounts.length },
        { kind: 'Categories', count: categories.length },
        { kind: 'Budgets', count: budgets.length },
        { kind: 'Recurring templates', count: templates.length },
        {
            kind: 'Template materializations',
            count: templateMaterializations,
            note: `Past ${monthsBack} months of bi-weekly paychecks + monthly bills`,
        },
        {
            kind: 'Sample transactions',
            count: proceduralTotal,
            note: `~${proceduralTransactionsPerMonth}/month: groceries, dining, coffee, gas, etc.`,
        },
        {
            kind: 'Revert pairs',
            count: 3,
            note: '"Wrong day" corrections — spread across the 6 months',
        },
    ];

    return {
        version: SEED_VERSION,
        items,
        accounts,
        categories,
        budgets,
        templates,
        proceduralTransactionsPerMonth,
        monthsBack,
    };
}
